version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # password for default user: elastic
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    environment:
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$CERTS_DIR/ca/ca.crt
      - ELASTICSEARCH_SSL_CERTIFICATE=$CERTS_DIR/es01/es01.crt
      - ELASTICSEARCH_SSL_KEY=$CERTS_DIR/es01/es01.key
    volumes:
      - certs:$CERTS_DIR
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - es01

  metricbeat:
    build: .
    environment:
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$CERTS_DIR/ca/ca.crt
      - ELASTICSEARCH_SSL_CERTIFICATE=$CERTS_DIR/es01/es01.crt
      - ELASTICSEARCH_SSL_KEY=$CERTS_DIR/es01/es01.key
      - ELASTICSEARCH_PROTOCOL=https
      - KIBANA_HOST=http://kibana:5601

    volumes:
      - certs:$CERTS_DIR
      - metricbeat-data01:/usr/share/metricbeat/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - es-network
    depends_on:
      - es01

volumes:
  es-data01:
    driver: local
  metricbeat-data01:
    driver: local
  certs:
    driver: local

networks:
  es-network:
    driver: bridge

  #   output.elasticsearch:
  # hosts: ["https://myEShost:9200"]
  # username: "metricbeat_writer"
  # password: "YOUR_PASSWORD"
